-- 小程序会员表
CREATE TABLE IF NOT EXISTS `miniapp_members` (
  `id` char(36) NOT NULL,
  `platform` varchar(20) NOT NULL DEFAULT 'wechat' COMMENT '小程序平台：wechat/toutiao',
  `appId` varchar(64) NOT NULL COMMENT '小程序 AppID',
  `openId` varchar(100) NOT NULL COMMENT '小程序 openId',
  `unionId` varchar(100) DEFAULT NULL COMMENT '小程序 unionId',
  `sessionKey` text DEFAULT NULL COMMENT '小程序 session_key',
  `nickName` varchar(100) DEFAULT NULL COMMENT '会员昵称',
  `avatarUrl` text DEFAULT NULL COMMENT '头像 URL',
  `phoneNumber` varchar(30) DEFAULT NULL COMMENT '手机号',
  `gender` varchar(20) DEFAULT NULL COMMENT '性别',
  `country` varchar(100) DEFAULT NULL COMMENT '国家',
  `province` varchar(100) DEFAULT NULL COMMENT '省份',
  `city` varchar(100) DEFAULT NULL COMMENT '城市',
  `loginCount` int NOT NULL DEFAULT 0 COMMENT '登录次数',
  `lastLoginAt` datetime DEFAULT NULL COMMENT '最后登录时间',
  `lastLoginIp` varchar(80) DEFAULT NULL COMMENT '最后登录 IP',
  `isActive` tinyint NOT NULL DEFAULT 1 COMMENT '状态：1正常，0禁用',
  `isAuthorization` varchar(1) NOT NULL DEFAULT '0' COMMENT '是否同意隐私协议：1是，0否',
  `remark` text DEFAULT NULL COMMENT '后台备注',
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `deletedAt` datetime(6) DEFAULT NULL COMMENT '删除时间（伪删除标记）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_miniapp_member_openid` (`platform`, `appId`, `openId`),
  KEY `IDX_miniapp_member_created` (`createdAt`),
  KEY `IDX_miniapp_member_phone` (`phoneNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='小程序会员表';
